#!/usr/bin/env bash
# Ducky Pool installer for Ubuntu 24.04+
#
# What it does:
#   1. Installs Docker if not present
#   2. Drops the app config into /opt/ducky-pool
#   3. Generates a strong RPC password
#   4. Builds the web + ckpool images
#   5. Starts everything via docker compose
#   6. Installs a systemd unit so it boots with the host
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/ducksdev/ducky-pool/main/install.sh | sudo bash
#
# Or from a local clone:
#   sudo ./install.sh
#
# Idempotent: safe to re-run. Won't touch your data dirs or RPC password
# on subsequent runs.

set -euo pipefail

#────────────────────────────── config ──────────────────────────────#

INSTALL_DIR="${INSTALL_DIR:-/opt/ducky-pool}"
DATA_DIR="${DATA_DIR:-/var/lib/ducky-pool}"
SERVICE_NAME="ducky-pool"
STRATUM_PORT="${STRATUM_PORT:-4567}"
WEB_PORT="${WEB_PORT:-4568}"
P2P_PORT="${P2P_PORT:-8333}"
BCHN_IMAGE="${BCHN_IMAGE:-zquestz/bitcoin-cash-node:latest}"

# Source files served from your repo. The installer can run standalone
# (downloads everything) or be invoked from a local checkout.
REPO_RAW="${REPO_RAW:-https://raw.githubusercontent.com/ducksdev/ducky-pool/main}"

#────────────────────────────── helpers ──────────────────────────────#

c_blue()  { printf '\033[1;34m%s\033[0m\n' "$*"; }
c_green() { printf '\033[1;32m%s\033[0m\n' "$*"; }
c_red()   { printf '\033[1;31m%s\033[0m\n' "$*" >&2; }

step() { c_blue "▶ $*"; }
ok()   { c_green "  ✓ $*"; }
die()  { c_red "✗ $*"; exit 1; }

require_root() {
    if [ "${EUID}" -ne 0 ]; then
        die "Run as root: sudo $0"
    fi
}

detect_local_clone() {
    # If this script is being run from inside a checkout that has the
    # service files alongside it, use those instead of downloading.
    local here
    here="$(cd "$(dirname "$0")" && pwd)"
    if [ -f "$here/services/web/Dockerfile" ] && [ -f "$here/services/ckpool/Dockerfile" ]; then
        SOURCE_MODE="local"
        SOURCE_DIR="$here"
    else
        SOURCE_MODE="remote"
        SOURCE_DIR=""
    fi
}

fetch_or_copy() {
    local rel="$1"
    local dest="$2"
    if [ "$SOURCE_MODE" = "local" ]; then
        cp "$SOURCE_DIR/$rel" "$dest"
    else
        curl -fsSL "$REPO_RAW/$rel" -o "$dest" \
            || die "Could not download $rel from $REPO_RAW"
    fi
}

#────────────────────────────── steps ──────────────────────────────#

install_docker() {
    if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
        ok "Docker + Compose already installed"
        return
    fi

    step "Installing Docker"
    apt-get update -y
    apt-get install -y ca-certificates curl gnupg

    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
        | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

    local codename
    codename="$(. /etc/os-release && echo "$VERSION_CODENAME")"
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/ubuntu $codename stable" \
        > /etc/apt/sources.list.d/docker.list

    apt-get update -y
    apt-get install -y \
        docker-ce docker-ce-cli containerd.io \
        docker-buildx-plugin docker-compose-plugin

    systemctl enable --now docker
    ok "Docker installed"
}

create_dirs() {
    step "Creating directories"
    mkdir -p \
        "$INSTALL_DIR/services/web/templates" \
        "$INSTALL_DIR/services/ckpool" \
        "$DATA_DIR/bchnode" \
        "$DATA_DIR/ckpool" \
        "$DATA_DIR/shared"
    ok "Layout ready under $INSTALL_DIR and $DATA_DIR"
}

generate_secrets() {
    step "Generating RPC credentials"
    local pass_file="$DATA_DIR/rpc.pass"
    if [ ! -s "$pass_file" ]; then
        head -c 24 /dev/urandom | base64 | tr -d '/+=' | head -c 32 > "$pass_file"
        chmod 600 "$pass_file"
        ok "Generated new RPC password at $pass_file"
    else
        ok "RPC password already exists, leaving it alone"
    fi
}

write_compose() {
    step "Writing docker-compose.yml"
    local rpc_pass
    rpc_pass="$(cat "$DATA_DIR/rpc.pass")"

    cat > "$INSTALL_DIR/docker-compose.yml" <<COMPOSE
# Generated by install.sh — do not edit by hand.
# Re-run install.sh to regenerate.

services:
  bchnode:
    image: ${BCHN_IMAGE}
    container_name: ducky-bchnode
    restart: unless-stopped
    stop_grace_period: 5m
    volumes:
      - ${DATA_DIR}/bchnode:/home/bitcoin/.bitcoin
    command:
      - bitcoind
      - -datadir=/home/bitcoin/.bitcoin
      - -server=1
      - -listen=1
      - -rpcbind=0.0.0.0
      - -rpcallowip=0.0.0.0/0
      - -rpcuser=bchrpc
      - -rpcpassword=${rpc_pass}
      - -rpcport=8332
      - -port=8333
      - -dbcache=512
      - -maxmempool=300
    ports:
      - "${P2P_PORT}:8333"

  ckpool:
    build: ./services/ckpool
    image: ducky-ckpool:local
    container_name: ducky-ckpool
    restart: unless-stopped
    stop_grace_period: 30s
    environment:
      BCH_RPC_HOST: bchnode
      BCH_RPC_PORT: 8332
      BCH_RPC_USER: bchrpc
      BCH_RPC_PASS: ${rpc_pass}
      STRATUM_PORT: ${STRATUM_PORT}
      PAYOUT_ADDRESS_FILE: /shared/payout.address
      POOL_SIG: "/ducky-pool/"
    volumes:
      - ${DATA_DIR}/shared:/shared:ro
      - ${DATA_DIR}/ckpool:/var/log/ckpool
    ports:
      - "${STRATUM_PORT}:${STRATUM_PORT}"
    depends_on:
      - bchnode

  web:
    build: ./services/web
    image: ducky-web:local
    container_name: ducky-web
    restart: unless-stopped
    stop_grace_period: 30s
    environment:
      FLASK_PORT: ${WEB_PORT}
      BCH_RPC_HOST: bchnode
      BCH_RPC_PORT: 8332
      BCH_RPC_USER: bchrpc
      BCH_RPC_PASS: ${rpc_pass}
      STRATUM_PORT: ${STRATUM_PORT}
      PAYOUT_ADDRESS_FILE: /shared/payout.address
      POOL_STATUS_FILE: /pool-logs/pool/pool.status
    volumes:
      - ${DATA_DIR}/shared:/shared
      - ${DATA_DIR}/ckpool:/pool-logs:ro
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - bchnode
COMPOSE
    chmod 600 "$INSTALL_DIR/docker-compose.yml"   # contains the RPC pass
    ok "docker-compose.yml written"
}

fetch_app_files() {
    step "Fetching app files"
    fetch_or_copy services/web/Dockerfile          "$INSTALL_DIR/services/web/Dockerfile"
    fetch_or_copy services/web/requirements.txt    "$INSTALL_DIR/services/web/requirements.txt"
    fetch_or_copy services/web/app.py              "$INSTALL_DIR/services/web/app.py"
    fetch_or_copy services/web/templates/index.html \
                                                   "$INSTALL_DIR/services/web/templates/index.html"
    fetch_or_copy services/ckpool/Dockerfile       "$INSTALL_DIR/services/ckpool/Dockerfile"
    fetch_or_copy services/ckpool/ckpool.conf.template \
                                                   "$INSTALL_DIR/services/ckpool/ckpool.conf.template"
    fetch_or_copy services/ckpool/entrypoint.sh    "$INSTALL_DIR/services/ckpool/entrypoint.sh"
    chmod +x "$INSTALL_DIR/services/ckpool/entrypoint.sh"
    ok "App files in place"
}

build_and_start() {
    step "Building images (ckpool compile takes a few minutes the first time)"
    cd "$INSTALL_DIR"
    docker compose build
    ok "Images built"

    step "Starting stack"
    docker compose up -d
    ok "Containers started"
}

install_systemd() {
    step "Installing systemd unit"
    cat > "/etc/systemd/system/${SERVICE_NAME}.service" <<UNIT
[Unit]
Description=Ducky Pool (BCH node + ckpool + dashboard)
Requires=docker.service
After=docker.service network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${INSTALL_DIR}
ExecStart=/usr/bin/docker compose up -d
ExecStop=/usr/bin/docker compose down
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
UNIT
    systemctl daemon-reload
    systemctl enable "${SERVICE_NAME}.service"
    ok "Service ${SERVICE_NAME} enabled — will start on boot"
}

print_summary() {
    local ip
    ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
    [ -z "$ip" ] && ip="<this-host>"

    echo
    c_green "════════════════════════════════════════════════════════════"
    c_green "  Ducky Pool is up."
    c_green "════════════════════════════════════════════════════════════"
    echo
    echo "  Dashboard :  http://${ip}:${WEB_PORT}"
    echo "  Stratum   :  stratum+tcp://${ip}:${STRATUM_PORT}"
    echo
    echo "  Next steps:"
    echo "    1. Open the dashboard, set a BCH payout address (legacy or CashAddr)."
    echo "    2. Wait for the BCH node to sync (~250 GB, hours-to-days)."
    echo "    3. Point miners at the stratum URL."
    echo
    echo "  Useful commands:"
    echo "    sudo systemctl status ${SERVICE_NAME}"
    echo "    sudo docker logs -f ducky-bchnode"
    echo "    sudo docker logs -f ducky-ckpool"
    echo "    sudo docker logs -f ducky-web"
    echo "    sudo docker compose -f ${INSTALL_DIR}/docker-compose.yml down"
    echo
}

#────────────────────────────── main ──────────────────────────────#

require_root
detect_local_clone

step "Source mode: $SOURCE_MODE"

install_docker
create_dirs
generate_secrets
fetch_app_files
write_compose
build_and_start
install_systemd
print_summary
